source 'https://rubygems.org'

gem 'cucumber'
gem 'rspec'
gem 'rake'
gem 'page-object', '~> 2.0'
gem 'data_magic'
gem 'activerecord', '3.2.1'
gem 'factory_girl'
#gem 'database_cleaner'
gem 'mysql2', '0.4.10'
gem 'activerecord-mysql2-adapter', '~> 0.0.3'
gem 'fig_newton'