source 'https://rubygems.org'

gem 'cucumber'
gem 'rspec'
gem 'rake'
gem 'page-object', '~> 2.0'
gem 'data_magic'
gem 'activerecord', '3.2.1'
gem 'factory_girl'
gem 'database_cleaner'
gem 'mysql2', '~> 0.3.10'